spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./database/h2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  h2:
    console.enabled: true

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

server:
  port: 80

logging:
  level:
    org:
      springframework:
        test: INFO
        web: INFO
