spring:
  profiles:
    active: local

server:
  port: 80

logging:
  level:
    org:
      springframework:
        test: INFO
        web: INFO

database:
  recipe:
    store-file: "I:\\Java Projects\\MyProjects\\cookbook\\database\\recipe.json"
