CREATE TABLE IF NOT EXISTS recipe (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  description VARCHAR(1000) DEFAULT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  preparation VARCHAR(10000) DEFAULT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci
);